name: Build and deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.1
        env:
          JEKYLL_PAT: ${{ secrets.PORTFOLIO_PAT }}
